name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: charu167/meal_planner_backend:latest
      
      - name: Verify pushed image
        run: docker pull charu167/meal_planner_backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            sudo docker pull charu167/meal_planner_backend:latest
            sudo docker stop meal_planner_backend || true
            sudo docker rm meal_planner_backend || true
            sudo docker run -d --name meal_planner_backend -p 3001:3001 charu167/meal_planner_backend:latest
    